### ISSUE TITLE
Unexpected errors in text_styling.lua in LuanalysisTypesDemo

### ISSUE THREAD

**Issue by E-Fir** [Benjamin-Dobell/IntelliJ-Luanalysis#37] opened 2021-01-08 08:24 UTC
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | CLion 2020.3.1 Build #CL-203.6682.181
 Luanalysis version | 1.2.1-IDEA203
 OS                        | Windows 10 x64

Type safety flags checked in the settings:
* Unknown type (any) is indexable
* Unknown type (any) is callable

What are the steps to reproduce this issue?
------------------------------------------------
1. open https://github.com/Benjamin-Dobell/LuanalysisTypesDemo/src/text_styling.lua in IDE

What happens?
-------------
I see errors that is not tagged with the "Expected error" comment like as in other error cases.

What were you expecting to happen?
-----------------------------------------
No errors or the "Expected error" tags.

Any logs, error output, etc?
------------------------------
[screenshot](https://prnt.sc/wiuabk)

1. Type mismatch. Required: 'V[]' Found: 'any' 
1. No such indexer '[1]' found on type 'any' 
1. No such indexer '[string]' found on type 'table' 
1. No such member 'hi' found on type 'any'
2. No such member 'blarg' found on type 'void'

**Comment by Benjamin-Dobell** [comment] 2021-01-08 11:43
Thanks for the report.

This one I am able to reproduce. Looks like I broke some `any` behaviour in a recent update.

> * Unknown type (any) is indexable
> * Unknown type (any) is callable

The majority of the tests run with these disabled as for the most part I'm trying to test the strictest type checking. I'll fix the problem and add some tests specifically with these options enabled to mitigate any further regressions.

**Comment by Benjamin-Dobell** [comment] 2021-01-14 17:58
Should be fixed in v1.2.2. Currently being reviewed by Jetbrains, but you can grab it from Github in the meantime.

**Closed by Benjamin-Dobell** 2021-01-14 17:58 UTC
Labels: bug
