### ISSUE TITLE
types not being excluded from type union when comparing type() or against "~= nil"

### ISSUE THREAD

**Issue by Xseba360** [Benjamin-Dobell/IntelliJ-Luanalysis#100] opened 2021-09-11 11:54 UTC
## Environment

Name | Version
-----|--------
IDEA version | WebStorm 2021.2.1
Luanalysis version | 1.3.0
OS | Windows 10
 
 
## Preferences

(Preferences -> Languages & Frameworks > Luanalysis)

### Lua

Name | Setting  
-----|--------
Language level | Lua 5.4

### Type Safety

Name | Setting
-----|--------
Strict nil checks | ☑️
Unknown type (any) is indexable | ☑️
Unknown type (any) is callabale | ☑️

## What are the steps to reproduce this issue?

1. enable all of the type safety inspections

## What happens?

```lua
---TestClass
---@param options TestClassOptions
---@returns TestClass
function TestClass(options)
    ---@class TestClass
    local self = {}

    ---@type string
    self.firstOption = 'test'

    ---@type number
    self.secondOption = 42

    if options.firstOption ~= nil then
        self.firstOption = options.firstOption -- Type mismatch. Required: 'string' Found: 'nil | string' 
    end
    if type(options.secondOption) == 'number' then
        self.secondOption = options.secondOption -- Type mismatch. Required: 'number' Found: 'nil | number' 
    end
    return self
end 

---TestClassOptions
---@shape TestClassOptions
---@field firstOption string|nil optional
---@field secondOption number|nil optional as well 
```

L15 and L18 show a type mismatch warning like:
`Type mismatch. Required: 'string' Found: 'nil | string' `

## What were you expecting to happen?

If the `options.firstOption` and `options.secondOption` was compared against `nil`, the found type should have excluded `nil` since at that point neither of these can actually be `nil`. Same applies to comparing `type(options.secondOption) == 'number'`. After that comparison type should be explicitly set to 'number'

**Comment by Benjamin-Dobell** [comment] 2021-09-11 11:59
Duplicate of #4 / #63

Feature is planned, although there are bugs that need to be fixed first. Checkout those issues for more info.

**Closed by Benjamin-Dobell** 2021-09-11 11:59 UTC
