### ISSUE TITLE
Restrict type of local variable after an early return

### ISSUE THREAD

**Issue by rillig** [Benjamin-Dobell/IntelliJ-Luanalysis#97] opened 2021-08-21 07:35 UTC
Environment
--------------
   name   |   version  
----------|----------
 Luanalysis version | v1.3.0

What are the steps to reproduce this issue?
------------------------------------------------
~~~lua
---@return nil | string[]
local function load_lines(fname)
  return { "first", "second" }
end

local function process_lines(fname)
  local lines = load_lines(fname)
  if lines == nil then
    return nil, nil
  end
  for lineno, line in ipairs(lines) do
  end
end
~~~

What happens?
-------------
For the expression `ipairs(lines)`, Luanalysis reports:
> Type mismatch. Required: 'string[]' Found: 'nil | string[]'

What were you expecting to happen?
-----------------------------------------
No error since the case of `lines == nil` leads to an early `return`.

**Comment by Benjamin-Dobell** [comment] 2021-08-21 08:22
Duplicate of https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/issues/4

**Closed by Benjamin-Dobell** 2021-08-21 08:22 UTC
